// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_OyERWBjIFuZckvYWewI_Ho7AXLy40k',
    appId: '1:266766294682:web:464f5a9d89c264d0b88923',
    messagingSenderId: '266766294682',
    projectId: 'test-874ae',
    authDomain: 'test-874ae.firebaseapp.com',
    databaseURL: 'https://test-874ae-default-rtdb.firebaseio.com',
    storageBucket: 'test-874ae.appspot.com',
    measurementId: 'G-EQQF2WJDT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAu53_p6ZqXGuG3b_m92JalaKhPP8FCas',
    appId: '1:266766294682:android:492922fae07a7932b88923',
    messagingSenderId: '266766294682',
    projectId: 'test-874ae',
    databaseURL: 'https://test-874ae-default-rtdb.firebaseio.com',
    storageBucket: 'test-874ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXTGyl50I0LFkWHUA1dxknM73eTGTlWY',
    appId: '1:266766294682:ios:4ea9772bb549d068b88923',
    messagingSenderId: '266766294682',
    projectId: 'test-874ae',
    databaseURL: 'https://test-874ae-default-rtdb.firebaseio.com',
    storageBucket: 'test-874ae.appspot.com',
    iosClientId: '266766294682-79upkhsn6rt7vqgnpqrjkfgpdlema5qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXTGyl50I0LFkWHUA1dxknM73eTGTlWY',
    appId: '1:266766294682:ios:4ea9772bb549d068b88923',
    messagingSenderId: '266766294682',
    projectId: 'test-874ae',
    databaseURL: 'https://test-874ae-default-rtdb.firebaseio.com',
    storageBucket: 'test-874ae.appspot.com',
    iosClientId: '266766294682-79upkhsn6rt7vqgnpqrjkfgpdlema5qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterapp',
  );
}
